### ISSUE TITLE
dont worked on Leaf 26.2(paper fork)

### ISSUE THREAD

**Issue by AllFiRE0** [imDaniX/WGExtender#19]
```
[11:44:46] [Server thread/INFO]: [WGExtender] Enabling WGExtender v3.6.0-SNAPSHOT-x
[11:44:46] [Server thread/ERROR]: Error occurred while enabling WGExtender v3.6.0-SNAPSHOT-x (Is it up to date?)
java.lang.NoSuchMethodError: 'net.kyori.adventure.util.Buildable$Builder net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer.toBuilder()'
	at WGExtenderX-3.6.0-SNAPSHOT.jar//wgextender.config.message.MessagesProvider$Serializer.fixup(MessagesProvider.java:180) ~[?:?]
	at WGExtenderX-3.6.0-SNAPSHOT.jar//wgextender.config.message.MessagesProvider$Serializer.<clinit>(MessagesProvider.java:168) ~[?:?]
	at WGExtenderX-3.6.0-SNAPSHOT.jar//wgextender.config.message.MessagesProvider.<init>(MessagesProvider.java:36) ~[?:?]
	at WGExtenderX-3.6.0-SNAPSHOT.jar//wgextender.config.ConfigurationProvider.<init>(ConfigurationProvider.java:56) ~[?:?]
	at WGExtenderX-3.6.0-SNAPSHOT.jar//wgextender.WGExtender.onEnable(WGExtender.java:90) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[leaf-api-26.2.build.36-alpha.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:201) ~[leaf-26.2.jar:26.2-36-b710632]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-26.2.jar:26.2-36-b710632]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[leaf-api-26.2.build.36-alpha.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652) ~[leaf-26.2.jar:26.2-36-b710632]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:609) ~[leaf-26.2.jar:26.2-36-b710632]
	at net.minecraft.server.MinecraftServer.initPostWorld(MinecraftServer.java:702) ~[leaf-26.2.jar:26.2-36-b710632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:404) ~[leaf-26.2.jar:26.2-36-b710632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1344) ~[leaf-26.2.jar:26.2-36-b710632]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[leaf-26.2.jar:26.2-36-b710632]
	at java.base/java.lang.Thread.run(Thread.java:1474) ~[?:?]
[11:44:46] [Server thread/INFO]: [WGExtender] Disabling WGExtender v3.6.0-SNAPSHOT-x
```

**Comment by imDaniX** [comment]
Try the snapshot build from https://github.com/imDaniX/WGExtender/actions/runs/29824309001
